version: '3.9'

services:
  fibery-app-db:
    image: mysql:latest
    env_file:
      - .env
    command: [ 'mysqld','--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci','--default-time-zone=+02:00','--default-authentication-plugin=mysql_native_password' ]
    ports:
      - "3310:3306"
    networks:
      - fibery-app-network
  fibery-app:
    build:
      dockerfile: Dockerfile
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - fibery-app-db
    networks:
      - fibery-app-network
    tty: true
    restart: unless-stopped
networks:
  fibery-app-network:
    driver: bridge